"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */

import Link from "next/link";
import { useEffect, useState } from "react";
import { AdminNav } from "./AdminNav";

const money = (value: number) => value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const date = (value: string) => new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" });
export function AdminDashboard() { const [data, setData] = useState<any>(null); const [error, setError] = useState(""); useEffect(() => { const frame = window.requestAnimationFrame(() => { void fetch("/api/admin/dashboard", { cache: "no-store" }).then(async (r) => { const result = await r.json(); if (!r.ok) setError(result.error); else setData(result); }); }); return () => window.cancelAnimationFrame(frame); }, []); if (error) return <main className="min-h-screen bg-[#090a0c] p-8 text-red-400">{error}</main>; if (!data) return <main className="min-h-screen bg-[#090a0c] p-8 text-zinc-400">Carregando dashboard...</main>; const metrics = [["Pedidos", data.metrics.totalOrders], ["Aguardando pagamento", data.metrics.awaiting], ["Pagamento confirmado", data.metrics.confirmed], ["Enviados", data.metrics.shipped.length], ["Entregues", data.metrics.delivered], ["Produtos ativos", data.metrics.activeProducts], ["Clientes", data.metrics.customers], ["Faturamento válido", money(data.metrics.revenue)]]; return <main className="min-h-screen bg-[#090a0c] px-5 py-8 text-white lg:px-8"><div className="mx-auto max-w-7xl"><header className="border-b border-white/10 pb-8"><p className="text-xs font-bold uppercase tracking-[.3em] text-red-500">Operação</p><h1 className="mt-3 text-4xl font-black">Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Visão geral da CONEXÃO PY.</p></header><AdminNav /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{metrics.map(([label, value]) => <div key={String(label)} className="rounded-2xl border border-white/10 bg-[#101216] p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-3 text-2xl font-black">{value}</p></div>)}</div><section className="mt-8 rounded-2xl border border-white/10 bg-[#101216] p-6"><h2 className="text-xl font-black">Últimos pedidos</h2><div className="mt-5 grid gap-3">{data.recentOrders.map((order: any) => <Link key={order.id} href={`/admin/pedidos/${order.id}`} className="flex flex-wrap items-center justify-between gap-3 border-b border-white/10 pb-3 text-sm hover:text-red-400"><span className="font-bold">#{order.order_number}</span><span className="text-zinc-400">{order.customer_name}</span><span>{money(Number(order.total))}</span><span className="text-zinc-500">{order.status}</span><span className="text-xs text-zinc-600">{date(order.created_at)}</span></Link>)}</div></section></div></main>; }
